# This is a basic workflow to help you get started with Actions

name: Build
permissions:
 contents: write

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "set up environment"
        run: |
          apt install openjdk-21-jre make
      # Checks-out your repository under $GITcreative_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Pack
        run: |
          make
          echo 'VERSION='$(cat pakku.json | head -n 3 | tail -n 1 | tail -c 8 | head -c -3) >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Release Automatically Generated by software... Please change draft to add changelog.
          draft: true
          prerelease: false
      - name: Upload Release Asset
        id: upload-client-pack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-GITHUB-actions/#passing-data-to-future-steps 
          asset_path: ./build/modrinth/lavacraft4-${{ env.VERSION }}.mrpack
          asset_name: lavacraft4-client-${{ env.VERSION }}.mrpack
          asset_content_type: application/zip
      - name: Upload Release Asset
        id: upload-server-pack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-GITHUB-actions/#passing-data-to-future-steps 
          asset_path: ./build/serverpack/lavacraft4-${{ env.VERSION }}.zip
          asset_name: lavacraft4-serverpack-${{ env.VERSION }}.zip
          asset_content_type: application/zip